[package]
name = "bevy_uniform_grid_2d"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15", default-features = false }
glam = "0.29.3"
rustc-hash = "2.1.1"
smallvec = "1.15.1"
thiserror = "2.0.12"
